---
abstract: 'Alien package for the UDUNITS-2 physical unit manipulation and conversion library'
author:
  - 'Zakariyya Mughal <zmughal@cpan.org>'
build_requires:
  Alien::Build: '0.32'
  Alien::Build::MM: '0.32'
  ExtUtils::MakeMaker: '6.52'
  File::Basename: '0'
  Module::Load: '0'
  Test::More: '0'
  Test::Number::Delta: '0'
  perl: '5.006'
configure_requires:
  Alien::Build: '1.40'
  Alien::Build::MM: '0.32'
  ExtUtils::MakeMaker: '6.52'
  perl: '5.006'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-UDUNITS2
recommends:
  Inline: '0.67'
  Inline::C: '0.62'
requires:
  Alien::Base: '0.038'
  Exporter: '0'
  File::Spec: '0'
  Perl::OSType: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/EntropyOrg/p5-Alien-UDUNITS2
  repository: https://github.com/EntropyOrg/p5-Alien-UDUNITS2.git
version: '0.008'
x_alienfile:
  generated_by: 'Dist::Zilla::Plugin::AlienBuild version 0.31'
  requires:
    share:
      Alien::gmake: '0.14'
      Archive::Tar: '0'
      Config: '0'
      HTTP::Tiny: '0.044'
      IO::Socket::SSL: '1.56'
      IO::Zlib: '0'
      Mojo::DOM: '0'
      Mojolicious: '7.00'
      Net::SSLeay: '1.49'
      Sort::Versions: '0'
      URI: '0'
      URI::Escape: '0'
    system: {}
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
