---
abstract: 'Alien package for the UDUNITS-2 physical unit manipulation and conversion library'
author:
  - 'Zakariyya Mughal <zmughal@cpan.org>'
build_requires:
  File::Basename: 0
  Module::Load: 0
  Test::More: 0
configure_requires:
  Alien::Base: 0.005
  File::ShareDir: 1.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-UDUNITS2
requires:
  Alien::Base: 0.005
  Exporter: 0
  File::ShareDir: 1.03
  File::Spec: 0
  Perl::OSType: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/zmughal/p5-Alien-UDUNITS2
  repository: https://github.com/zmughal/p5-Alien-UDUNITS2.git
version: 0.001
